rich_help_panel_input_options = "Input options"
rich_help_panel_output_options = "Output options"
rich_help_panel_selection_options = "Selection options"
rich_help_panel_chunking_parameters = "Chunking options"
rich_help_panel_chunk_sizes = "Chunk sizes"
rich_help_panel_nccopy = "nccopy options"
rich_help_panel_dask_configuration = "Dask configuration"
rich_help_panel_diagnose = "Diagnose chunking layout"
rich_help_panel_suggest = "Suggest chunking layout"
rich_help_panel_rechunking = "Rechunk data"
rich_help_panel_reference = "Create references"
rich_help_panel_combine = "Combine references"
rich_help_panel_zarr = "Zarr"
rich_help_panel_select = "Select from time series"
rich_help_panel_select_references = "Select from Kerchunk references"
rich_help_panel_read_performance = (
    "[bold magenta reverse] :timer_clock: Read performance [/bold magenta reverse]"
)
rich_help_panel_time_series = "Time series"
rich_help_panel_data_variables = "Data variables"
rich_help_panel_advanced_options = "Advanced"
rich_help_panel_output_data_structure = "Output data structure"
rich_help_panel_plotting = "Plot"
